In [26]:
import tensorflow as tf
import random
import pandas
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense

In [27]:
#Data_collecting and pre_processing
headers=['oxygen', 'bpm', 'temp', 'hrv', 'final']
#data from csv
sample=pd.read_csv("C:\\Mtech\\advanced_microprocessor_systems\\Assignment\\sample.csv")
print(sample)
#create result set
sample_labels = sample.pop('final')
sample_features = sample.copy()
#create features set
sample_features = np.array(sample_features)
#print features and result
print(sample_features)
print(sample_labels)

     oxygen  bpm  temp    hrv  final
0        96   70  38.9  67.60      1
1        93   54  36.2  40.46      1
2       100  121  38.4  61.68      1
3        94  113  37.9  47.77      1
4        92   43  39.6  42.03      2
..      ...  ...   ...    ...    ...
995      93   98  37.2  48.12      1
996      97   86  38.6  49.70      1
997      97  137  37.4  50.34      2
998      93   71  38.6  48.41      1
999      92   50  38.2  46.80      2

[1000 rows x 5 columns]
[[ 96.    70.    38.9   67.6 ]
 [ 93.    54.    36.2   40.46]
 [100.   121.    38.4   61.68]
 ...
 [ 97.   137.    37.4   50.34]
 [ 93.    71.    38.6   48.41]
 [ 92.    50.    38.2   46.8 ]]
0      1
1      1
2      1
3      1
4      2
      ..
995    1
996    1
997    2
998    1
999    2
Name: final, Length: 1000, dtype: int64


In [36]:
#splitting the features and results into train and test
nsamples= 1000
tflite_model_name ='new_model'
train_split =  int(0.8 * nsamples)
test_ratio= 0.2
test_split = int(test_ratio*nsamples)
sample_features_train, sample_features_test= np. split(sample_features,[test_split] )
sample_labels_train, sample_labels_test= np. split(sample_labels, [test_split])

In [29]:
#normalization and training
samples_features_train = tf.keras.utils.normalize(sample_features_train, axis=1)
sample_features_test = tf.keras.utils.normalize(sample_features_test, axis=1)

model = tf.keras.Sequential()
model.add(Dense(32, input_shape=(4,)))
model.add(tf.keras.layers.Dense(units=128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(units=128, activation=tf.nn.relu))
model.add(tf.keras.layers.Dense(units=1, activation=tf.nn.softmax))
              


In [30]:
#compilation
model.compile(optimizer='adam', loss='mae', metrics=['accuracy'])

In [31]:
#train the model
model.fit(sample_features_train, sample_labels_train, epochs=50)
#testing the model for accuracy
loss, accuracy = model.evaluate(sample_features_test, sample_labels_test)
print(loss)
print(accuracy)

Epoch 1/50
7/7 [==============================] - 0s 4ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 2/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 3/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 4/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 5/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 6/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 7/50
7/7 [==============================] - 0s 1ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 8/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 9/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 10/50
7/7 [==============================] - 0s 3ms/step - loss: 0.7050 - accuracy: 0.2950
Epoch 11/50
7/7 [======================

In [32]:
model.save("new_model.h5")

In [33]:
print('Keras'+tf.keras.__version__)

Keras2.6.0


In [34]:
print('Tensorflow'+ tf.__version__)


Tensorflow2.9.1


In [35]:
#convert keras model into tensorflowlite model
converter= tf.lite.TFLiteConverter.from_keras_model(model)
#converter.optimizations=[tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
tflite_model=converter.convert()


with open('new_model.tflite', 'wb') as f:
    f.write(tflite_model)

#open(tflite_model_name + '.tflite', wb).write(tflite_model)